---
#Installing Erlang from official repo
- name: Downloading Erlang's repo
  get_url: url=http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb dest=/tmp/erlang-solutions_1.0_all.deb

- name: Installing Erlang's repo
  apt: deb=/tmp/erlang-solutions_1.0_all.deb

- name: Installing Erlang from official repo
  apt: name=erlang update_cache=yes

# RabbitMQ official install
- name: "add the official rabbitmq repository's key"
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
  when: not rabbitmq_os_package

- name: add the official rabbitmq repository
  copy:
    src=rabbitmq.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo
  when: not rabbitmq_os_package

- name: install rabbitmq-server
  apt: name=rabbitmq-server update_cache=yes

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
