---

- name: install EPEL repository (RedHat)
  command: "{{ item }}"
  with_items:
    - wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - rpm -Uvh epel-release-6*.rpm

- name: install rabbitmq-server dependencies (RedHat)
  yum: name="{{ item }}" state=present
  with_items:
    - erlang
    - libselinux-python

- name: install rabbitmq-server from URL (RedHat)
  yum: name={{ rabbitmq_binary_url }}/{{ rabbitmq_binary_rpm_filename }} state=present

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
