---
- name: install EPEL repository (RedHat)
  yum: name="{{ epel_package_rpm }}" state=present

- name: install rabbitmq-server dependencies (RedHat)
  yum: name="{{ item }}" state=present
  with_items:
    - erlang
    - libselinux-python

- name: install rabbitmq-server (RedHat)
  yum: name="{{ rabbitmq_server_package_rpm }}" state=present

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
