---
- name: create the ssl folder for rabbitmq
  file:
    path=/etc/rabbitmq/ssl/
    owner={{ rabbitmq_user }}
    group={{ rabbitmq_group }}
    mode=0750
    state=directory
  when: rabbitmq_ssl

- name: copy the ssl certificates
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ rabbitmq_user }}
    group={{ rabbitmq_group }}
    mode=0640
  with_items:
    - src: "{{ rabbitmq_cacert }}"
      dest: "{{ rabbitmq_conf_ssl_options_cacertfile }}"
    - src: "{{ rabbitmq_server_key }}"
      dest: "{{ rabbitmq_conf_ssl_options_keyfile }}"
    - src: "{{ rabbitmq_server_cert }}"
      dest: "{{ rabbitmq_conf_ssl_options_certfile }}"
  when: rabbitmq_ssl

- name: generate the configuration of rabbitmq
  template:
    src=rabbitmq.config.j2
    dest=/etc/rabbitmq/rabbitmq.config
    owner={{ rabbitmq_user }}
    group={{ rabbitmq_group }}
    mode=0644
  register: cluster_configuration
  notify: restart rabbitmq-server

- name: generate environment-specific configuration
  template:
    src=rabbitmq-env.conf.j2
    dest=/etc/rabbitmq/rabbitmq-env.conf
    owner={{ rabbitmq_user }}
    group={{ rabbitmq_group }}
    mode=0644
  notify: restart rabbitmq-server
  when: rabbitmq_conf_env is defined
