---
# ################
# Playbook control
# ################

# Plugins
rabbitmq_plugins: []
rabbitmq_new_only: 'no'

# VHOST
rabbitmq_vhost_definitions: []
rabbitmq_users_definitions: []

# Avoid setting up federation
rabbitmq_federation: false

# Avoid setting up clustering
rabbitmq_clustering: false

# defaults file for rabbitmq
rabbitmq_cacert     : "cacert"
rabbitmq_server_key : "server_key"
rabbitmq_server_cert: "server_cert"
rabbitmq_ssl        : true

# ######################
# RabbitMQ Configuration
# ######################

# rabbitmq TCP configuration
rabbitmq_conf_tcp_listeners_address: ''
rabbitmq_conf_tcp_listeners_port: 5672

# rabbitmq SSL configuration
rabbitmq_conf_ssl_listeners_address           : '0.0.0.0'
rabbitmq_conf_ssl_listeners_port              : 5671
rabbitmq_conf_ssl_options_cacertfile          : "/etc/rabbitmq/ssl/cacert.pem"
rabbitmq_conf_ssl_options_certfile            : "/etc/rabbitmq/ssl/server_cert.pem"
rabbitmq_conf_ssl_options_keyfile             : "/etc/rabbitmq/ssl/server_key.pem"
rabbitmq_conf_ssl_options_fail_if_no_peer_cert: "true"


rabbitmq_bin_path: "/usr/lib/rabbitmq/bin/"
rabbitmq_prefix: "/usr/lib/rabbitmq/"
