---
- name: create the ssl folder for rabbitmq
  file:
    path=/etc/rabbitmq/ssl/
    owner=rabbitmq
    group=rabbitmq
    mode=0750
    state=directory
  when: rabbitmq_ssl

- name: copy the ssl certificates
  copy:
    src=files/rabbitmq_{{ item }}.pem
    dest=/etc/rabbitmq/ssl/{{ item }}.pem
    owner=rabbitmq
    group=rabbitmq
    mode=0640
    backup=yes
  with_items:
    - "{{ rabbitmq_cacert }}"
    - "{{ rabbitmq_server_key }}"
    - "{{ rabbitmq_server_cert }}"
  when: rabbitmq_ssl

- name: generate the configuration of rabbitmq
  template:
    src=rabbitmq.config.j2
    dest=/etc/rabbitmq/rabbitmq.config
    owner=rabbitmq
    group=rabbitmq
    mode=0644
    backup=yes
  notify: restart rabbitmq-server

- name: enable plugins
  rabbitmq_plugin: names={{ rabbitmq_plugins | join(',') }} state=enabled new_only={{ rabbitmq_new_only }}
    plugins_path={{rabbitmq_bin_path}}
  notify: restart rabbitmq-server
  when: rabbitmq_plugins != []

- name: get the list of active plugins to disable
  command: "{{rabbitmq_bin_path}}/rabbitmq-plugins list -e -m"
  register: result
  when: rabbitmq_plugins == []

- name: disable plugins if none added in the configuration
  rabbitmq_plugin: name={{ item }} state=disabled
    plugins_path={{rabbitmq_bin_path}}
  notify: restart rabbitmq-server
  with_items: result.stdout_lines
  when: rabbitmq_plugins == []

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes

