---
- name: active the federation plugin
  rabbitmq_plugin: names=rabbitmq_federation state=enabled new_only=yes
  register: federation_plugin

- name: restart RabbitMQ to be able to setup federation
  service: name=rabbitmq-server state=restarted
  when: federation_plugin.changed

- name: set the federation-upstream parameter
  rabbitmq_parameter:
    component=federation-upstream
    name="{{ item.name }}"
    vhost="{{ item.vhost | default('/', false) }}"
    value='{{ item.value }}'
  with_items: rabbitmq_federation_configuration

- name: set the policy for the federation
  rabbitmq_policy:
    name={{ item.name }}
    vhost={{ item.vhost | default('/', false) }}
    pattern="{{ item.pattern }}"
    tags="{{ item.tags }}"
  with_items: rabbitmq_policy_configuration

- name: set the local username for the federation
  rabbitmq_parameter:
    component=federation
    name=local-username
    value='"{{ item.local_username | default( 'guest', false ) }}"'
    vhost={{ item.vhost | default( '/', false) }}
    state=present
  with_items: rabbitmq_federation_configuration
