---

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: centos.yml
  when: ansible_os_family == 'RedHat'

- include: common.yml

- include: federation.yml
  when: rabbitmq_federation

- include: clustering.yml
  when: rabbitmq_clustering

# only run this play on the first node of the cluster
- include: vhost.yml
  when: groups.rabbitmq_servers[0] == inventory_hostname
